FROM node:12

# Create app directory
WORKDIR /usr/src/app

# Install Development Tools
RUN npm -g config set user root
RUN npm i -g azure-functions-core-tools@3
RUN npm i -g dotnet-sdk-3.1

# Copy app
COPY ./settings-functions ./settings-functions
COPY ./settings-domain ./settings-domain

# Expose ports
EXPOSE 7073

# Run app
WORKDIR /usr/src/app/settings-functions
CMD [ "func", "start", "--port", "7073", "--cors", "http://localhost:5000", "--csharp" ]