version: '3.3'
services:
  auth-db:
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: 'iLovePineconeLP*123'
      MSSQL_PID: 'Express'
    ports:
      - '1433:1433'
    volumes:
      - 'auth-data:/var/opt/mssql/data'

volumes:
  auth-data:
