version: '3.3'
services:
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    ports:
      - '10000:10000'
      - '10001:10001'

  authfunctions:
    build:
      context: ../authentication-functions
      dockerfile: Dockerfile.Development
    environment:
      AzureWebJobsStorage: '${AZURE_STORAGE_CONNECTION_STRING}'
      Authentication_AccessTokenSecret: '${AUTHENTICATION_ACCESS_TOKEN_SECRET}'
      Authentication_RefreshTokenSecret: '7fG65iUioPT55s9oKwSngv28DDLH3jO9BErlbuID50uR876pmy-yWfRn_SK46nH6lG14vtnZOssYP6_JvDRuaYpa1dSImDi7bijYt24ZzosOyoeeXSEF2_rHqIqlLAyyCEdDiPvUyyzIVNM-dIvnk5FMaoQdV56Gy-nvlTT-Wj8'
      Authentication_Issuer: '${AUTHENTICATION_ISSUER}'
      Authentication_Audience: '${AUTHENTICATION_AUDIENCE}'
    ports:
      - '7072:7072'

  pingerfunctions:
    build:
      context: ../blazor-purity-vanilla-functions
      dockerfile: Dockerfile.Development
    env_file:
      # Contains AzureSignalRConnectionString
      - pinger-functions-secrets.env
    environment:
      AzureWebJobsStorage: '${AZURE_STORAGE_CONNECTION_STRING}'
      SERVER_IP: 'purityvanilla.com'
      SERVER_NAME: 'Purity Vanilla'
      SERVER_HAS_QUEUE: 'true'
      SERVER_MAX_PLAYERS_EXCLUDING_QUEUE: '75'
    ports:
      - '7071:7071'

  settingsfunctions:
    build:
      context: ../
      dockerfile: settings-functions/Dockerfile.Development
    environment:
      AzureWebJobsStorage: '${AZURE_STORAGE_CONNECTION_STRING}'
      Authentication_AccessTokenSecret: '${AUTHENTICATION_ACCESS_TOKEN_SECRET}'
      Authentication_Issuer: '${AUTHENTICATION_ISSUER}'
      Authentication_Audience: '${AUTHENTICATION_AUDIENCE}'
    ports:
      - '7073:7073'

volumes:
  auth-data:
