name: Build

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - 'bpv-win/v*'
      - 'bpv-osx/v*'
    paths-ignore:
      - '**/README.md'
  pull_request:
    branches:
      - '*'

env:
  PYTHON_PINGER_PROJECT_DIRECTORY: ./pinger/Scripts

jobs:
  build:
    runs-on: windows-latest
    steps:
      # Setup
      - uses: actions/checkout@v2

      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x

      # Python Pinger
      - name: Install pipenv
        run: pip install pipenv

      - name: Install Python Pinger dependencies
        run: pipenv install
        working-directory: ${{ env.PYTHON_PINGER_PROJECT_DIRECTORY }}

      - name: Build Python Pinger
        run: pipenv run build
        working-directory: ${{ env.PYTHON_PINGER_PROJECT_DIRECTORY }}

      # .NET
      - name: Restore .NET packages
        run: dotnet restore

      - name: Build .NET projects
        run: dotnet build --no-restore --configuration Release

      - name: Test .NET projects
        run: dotnet test --no-restore --no-build --configuration Release
