name: Deploy Blazor Purity Vanilla (Windows)

on:
  push:
    tags:
      - 'bpv-win/v*'

env:
  BLAZOR_PURITY_VANILLA_PROJECT_DIRECTORY: ./blazor-purity-vanilla
  EXE_PATH: ./blazor-purity-vanilla/bin/Desktop/*.exe

jobs:
  build:
    runs-on: windows-latest
    steps:
      # Setup
      - uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x

      - name: Setup Electron.NET CLI
        run: dotnet tool install ElectronNET.CLI -g

      # Blazor Purity Vanilla
      - name: Build Blazor Purity Vanilla
        run: electronize build /target win
        working-directory: ${{ env.BLAZOR_PURITY_VANILLA_PROJECT_DIRECTORY }}

      # Release
      - uses: olegtarasov/get-tag@v2
        id: tagName
        with:
          tagRegex: 'bpv-win/(.*)'

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ steps.tagName.outputs.tag }} (Windows)

      - name: Upload Release
        uses: csexton/release-asset-action@v2
        with:
          pattern: ${{ env.EXE_PATH }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          release-url: ${{ steps.create_release.outputs.upload_url }}
