name: Deploy Blazor Purity Vanilla (OSX)

on:
  push:
    tags:
      - 'bpv-osx/v*'
    paths-ignore:
      - '**/README.md'

env:
  PYTHON_PINGER_PROJECT_DIRECTORY: ./pinger/Scripts
  BLAZOR_PURITY_VANILLA_PROJECT_DIRECTORY: ./blazor-purity-vanilla
  DMG_PATH: ./blazor-purity-vanilla/bin/Desktop/*.dmg

jobs:
  build:
    runs-on: macos-latest
    steps:
      # Setup
      - uses: actions/checkout@v2

      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x

      - name: Setup Electron.NET CLI
        run: dotnet tool install ElectronNET.CLI -g

      # Python Pinger
      - name: Install pipenv
        run: pip install pipenv

      - name: Install Python Pinger dependencies
        run: pipenv install
        working-directory: ${{ env.PYTHON_PINGER_PROJECT_DIRECTORY }}

      - name: Build Python Pinger
        run: pipenv run build
        working-directory: ${{ env.PYTHON_PINGER_PROJECT_DIRECTORY }}

      # Blazor Purity Vanilla
      - name: Build Blazor Purity Vanilla
        run: electronize build /target osx
        working-directory: ${{ env.BLAZOR_PURITY_VANILLA_PROJECT_DIRECTORY }}

      # Release
      - name: Extract Tag
        uses: olegtarasov/get-tag@v2
        id: tagName
        with:
          tagRegex: 'bpv-osx/(.*)'

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ steps.tagName.outputs.tag }} (OSX)

      - name: Upload Release
        uses: csexton/release-asset-action@v2
        with:
          pattern: ${{ env.DMG_PATH }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          release-url: ${{ steps.create_release.outputs.upload_url }}
