name: Deploy Blazor Purity Vanilla (WASM)

on:
  push:
    tags:
      - "bpv-wasm/v*"
    paths-ignore:
      - "**/README.md"

env:
  STORAGE_ACCOUNT_KEY: ${{ secrets.WASM_STORAGE_ACCOUNT_KEY }}
  STORAGE_ACCOUNT_NAME: livestatuswasm
  STORAGE_CONTAINER_NAME: $web
  WASM_PROJECT_DIRECTORY: ./blazor-purity-vanilla-wasm
  PUBLISH_PATH: ./publish
  UPLOAD_DIR_PATH: ./blazor-purity-vanilla-wasm/publish/wwwroot

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      - name: Restore
        run: dotnet restore
        working-directory: ${{ env.WASM_PROJECT_DIRECTORY }}

      - name: Build
        run: dotnet build --no-restore --configuration Release
        working-directory: ${{ env.WASM_PROJECT_DIRECTORY }}

      - name: Publish
        run: dotnet publish --no-restore --no-build --configuration Release -o ${{ env.PUBLISH_PATH }}
        working-directory: ${{ env.WASM_PROJECT_DIRECTORY }}

      - name: Update base tag
        run: sed -i 's/<base href="\/" \/>/<base href="\/mc-live-status-purity-vanilla\/" \/>/g' ${{ env.UPLOAD_DIR_PATH }}/index.html

      - name: Deploy GH Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ env.UPLOAD_DIR_PATH }}
